### ISSUE TITLE
ember-cli-flow?

### ISSUE THREAD

**Issue by JackCA** [alexlafroscia/broccoli-flow#1]
Hey @alexlafroscia, I just discovered this library as I was searching for an ember-cli flow add-on. You reference your own repo "ember-cli-flow" in the README, but it's either private or doesn't exist. Do you plan on opening that up?

**Comment by alexlafroscia** [comment]
Yeah, it doesn't exist (yet). I kind of started down that path in a private addon but abandoned the whole project as I realized that I didn't really understand Flow or Broccoli enough at that time to make things really work. I feel like Ember is heading in the Typescript direction, so I don't really plan on continuing this either. Sorry 😦

**Comment by JackCA** [comment]
Cool. Thanks for the follow up. I'm sure it's an endeavor to get this done and I agree about Typescript direction things are heading in. 

I think I ended up discovering this because I got frustrated by some sort of issue with the ember-typescript addon... but I'll give that a shot again in a few months.

**Comment by boris-petrov** [comment]
Any update on this? CoffeeScript just got support for Flow and I intend to use it with Ember so I'm really interested in this project. :) Any news?

**Comment by alexlafroscia** [comment]
Definitely not. I should probably just remove this repo altogether; I'm not planning to continue this work.

Considering the fact that Ember's internals are increasingly being moved to TypeScript, I would imagine there will sooner or later be a really strong, out-of-the-box story for using TypeScript instead (there's currently [`ember-cli-typescript`](https://github.com/emberwatch/ember-cli-typescript) but I don't know much about it). Not knowing much about typed JS in general, I would just as soon try that out as attempt to use Flow.
